version: "3.8"

services:
  rtsp-server:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554"  # RTSP default port

  fake-stream:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    depends_on:
      - rtsp-server
    command: >
      -re -f lavfi -i testsrc=size=640x360:rate=30
      -vcodec libx264 -f rtsp rtsp://rtsp-server:8554/fakestream